### ISSUE TITLE
Theme assets broken when hosted on GitLab Pages

### ISSUE THREAD

**Issue by oxr463** [CONNECT-platform/codedoc#103]
This is from the browser console:

```
The resource from “https://foo.gitlab.io/docs/assets/codedoc-styles.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
```

Note: foo is not the real project name.

The published site is missing js and styling due to this error.

**Comment by loreanvictor** [comment]
I am unable to open `https://foo.gitlab.io`. Could you provide a live link? Or steps for reproduction (how did you deploy to GitLab pages)?

**Comment by oxr463** [comment]
Here is my GitLab CI/CD pipeline:

```
include:
  - template: Dependency-Scanning.gitlab-ci.yml

image: node:latest

pages:
  before_script:
    - npm i -g @codedoc/cli
    - npx codedoc install
  script:
    - npx codedoc build
    - mkdir public
    - cp -R docs public/
    - cp favicon.png public/
    - cp index.html public/
  artifacts:
    paths:
      - public
  only:
    - master
```
