### ISSUE TITLE
decreasing the width-size of TOC

### ISSUE THREAD

**Issue by zenhighzer** [CONNECT-platform/codedoc#126]
Hi there, 

codedoc is really nice! but one small question: 
is there a simple way to decrease the width of the toc? It seems to be too big :)

thanks and best regards! 

![grafik](https://user-images.githubusercontent.com/65350020/150318769-42bf75ef-5c0c-414c-8de7-90e2455aaf16.png)

**Comment by danielsitnik** [comment]
Do you use a large screen resolution?
The TOC size is dynamically calculated as 50% of the screen width minus 464 pixels: `calc(50vw - 464px)`.

**Comment by loreanvictor** [comment]
The TOC is given the id `-codedoc-toc`, so you can style it via some [custom stylesheets](https://codedoc.cc/docs/config/page#scripts-and-stylesheets) like this:

```css
#-codedoc-toc {
  width: ...
}

/** be sure to also provide an override for smaller screens **/
@media screen and (max-width: 1200px) {
  #-codedoc-toc {
      width: ...
  }
}
```
