### ISSUE TITLE
codedoc theme not highlighting syntax tokens of css/sass

### ISSUE THREAD

**Issue by gturpin-dev** [CONNECT-platform/codedoc#7]
Hi first I like a lot your project,

I want to know if it's possible to display code block with languages like Sass because it built with prism.js

like so :

```scss
%btn {
  padding: .5em 2em;
  text-decoration: none !important;
  user-select: none !important;
  outline: none !important;
  cursor: pointer;
  transition: .4s;
}
```

**Comment by loreanvictor** [comment]
Yes since prismjs supports sass, you can use code snippets with any language that is built in in prism.js.

It is however notable that the syntax highlighting might be a bit limited since a particular language might produce particular tokens that are not styled by the current codedoc theme. In such a case, you can add the highlighting via custom CSS for those tokens, and create an issue (or ideally a PR) for supporting those tokens in codedoc theming as well.

**Comment by gturpin-dev** [comment]
Thanks for response, but if i noticed that it's because this is not wokring for me, i tried this :
```scss | utilities/_buttons.scss
%btn {
  padding: .5em 2em;
  text-decoration: none !important;
  user-select: none !important;
  outline: none !important;
  cursor: pointer;
  transition: .4s;
}
```

and this :
```css | utilities/_buttons.scss
%btn {
  padding: .5em 2em;
  text-decoration: none !important;
  user-select: none !important;
  outline: none !important;
  cursor: pointer;
  transition: .4s;
}
```
And no one of these actually works for me
